# Generated by Django 5.2.17 on 2026-08-18 08:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Mamlakat nomi')),
                ('code', models.CharField(blank=True, help_text='Ixtiyoriy: UZ, KZ, TR kabi qisqartma.', max_length=3, verbose_name='ISO kodi')),
            ],
            options={
                'verbose_name': 'Mamlakat',
                'verbose_name_plural': 'Mamlakatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Shahar nomi')),
                ('population', models.PositiveIntegerField(help_text='Aholi soni (kishi).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aholisi')),
                ('is_capital', models.BooleanField(default=False, verbose_name='Poytaxtmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cities.country', verbose_name='Mamlakat')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['country__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='unique_city_per_country')],
            },
        ),
    ]
